openapi: 3.0.2
info:
  description: This is sample.
  title: sample API
  version: 1.0.0
servers:
- url: /
paths:
  /ping:
    get:
      description: ping
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
          description: ok
components:
  schemas:
    inline_response_200:
      example:
        status: OK
      properties:
        status:
          example: OK
          type: string
      type: object
